"""add rel

Revision ID: 07f089e8f04c
Revises: 61b3d1ae5ca5
Create Date: 2025-09-11 14:11:02.129802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07f089e8f04c'
down_revision: Union[str, Sequence[str], None] = '61b3d1ae5ca5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'course', 'user', ['teacher_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course', schema='public', type_='foreignkey')
    # ### end Alembic commands ###
