"""add rel

Revision ID: 4396a7fb60e2
Revises: 07f089e8f04c
Create Date: 2025-09-11 14:20:23.364337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4396a7fb60e2'
down_revision: Union[str, Sequence[str], None] = '07f089e8f04c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_teachers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['public.course.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['public.user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'course_id'),
    schema='public'
    )
    op.drop_constraint(op.f('course_teacher_id_fkey'), 'course', type_='foreignkey')
    op.drop_column('course', 'teacher_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('course_teacher_id_fkey'), 'course', 'user', ['teacher_id'], ['id'])
    op.drop_table('course_teachers', schema='public')
    # ### end Alembic commands ###
